In [25]:
import numpy as np

# Part 1

In [26]:
d = {"out": set()}
for line in open("11").read().split("\n"):
    a, b = line.split(": ")
    c = b.split(" ")
    d[a] = set(c)
indices = list(d.keys())

you = indices.index("you")
out = indices.index("out")

n = len(indices)

I = np.identity(n)

# A = adjacency matrix
A =  np.zeros(dtype=np.int32, shape=(n,n))
for (k,vs) in d.items():
    i = indices.index(k)
    for v in vs:
        j = indices.index(v)
        A[i,j] = 1
print(A)

# Approach 1: Taking powers of A and summing values: A + A^2 + A^3 + ...
M = I.copy()
t = 0
for _ in range(10):  # no idea if 10 is always enough lol
    t += M[you, out]
    M @= A  # matmul
print("part 1:", int(t))

# Alternative: works because its a DAG: T = (I - A)^-1 
T = np.linalg.inv(I - A).round().astype(int)

print("part 1, but cooler:",T[you, out])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
part 1: 585
part 1, but cooler: 585


# Part 2

In [27]:
import toposort

In [28]:
d = {"out": set()}
for line in open("11").read().split("\n"):
    a, b = line.split(": ")
    c = b.split(" ")
    d[a] = set(c)

# need to toposort because adjacency matrix needs to be upper triangular, and it only is if our indices are topologically sorted
# for part 1, it worked without this by chance, but for part 2 it causes issues
indices = toposort.toposort_flatten(d, sort=True)

out = indices.index("out")
svr = indices.index("svr")
dac = indices.index("dac")
fft = indices.index("fft")

n = len(indices)

I = np.identity(n)

# A = adjacency matrix
A =  np.zeros(dtype=np.int64, shape=(n,n))
for (k,vs) in d.items():
    i = indices.index(k)
    for v in vs:
        j = indices.index(v)
        A[i,j] = 1
print(A)

# T = (I - A)^-1 
T = np.linalg.inv(I - A).round().astype(int)

print("part 2: ", 
      (T[svr, fft] * T[fft, dac] * T[dac, out]) + # visiting fft before dac
      (T[svr, dac] * T[dac, fft] * T[fft, out]) # visiting dac before ftt
)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]
part 2:  349322478796032
